// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using new_usaha.Infrastructure.Persistence;

#nullable disable

namespace new_usaha.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221209125034_change")]
    partial class change
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("new_usaha.Domain.Entities.AddStockHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("GoodsStockId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("N")
                        .HasColumnType("int");

                    b.Property<decimal>("PriceChange")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PricePerItem")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PriceTotal")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("GoodsStockId");

                    b.ToTable("AddStockHistories");
                });

            modelBuilder.Entity("new_usaha.Domain.Entities.EmployeeJoin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("EnterpriseId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("EnterpriseRoleId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ExpiredTime")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("EnterpriseId");

                    b.HasIndex("EnterpriseRoleId");

                    b.ToTable("EmployeeJoins");
                });

            modelBuilder.Entity("new_usaha.Domain.Entities.EmployeePresence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Approval")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("ApprovalDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("EmployeePresenceCode_EndId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("EmployeePresenceCode_End_Id")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("EmployeePresenceCode_StartId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("EmployeePresenceCode_Start_Id")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("EnterpriseEmployeeId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<long>("NumberHours")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("UserApproverId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeePresenceCode_EndId");

                    b.HasIndex("EmployeePresenceCode_StartId");

                    b.HasIndex("EnterpriseEmployeeId");

                    b.ToTable("EmployeePresences");
                });

            modelBuilder.Entity("new_usaha.Domain.Entities.EmployeePresenceCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("EnterpriseId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsValid")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<long>("Tries")
                        .HasColumnType("bigint");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("EnterpriseId");

                    b.ToTable("EmployeePresenceCodes");
                });

            modelBuilder.Entity("new_usaha.Domain.Entities.EmployeeSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("EmployeeScheduleTypeId")
                        .HasColumnType("int");

                    b.Property<ulong>("EnterpriseEmployeeId")
                        .HasColumnType("bigint unsigned");

                    b.Property<Guid>("EnterpriseEmployeeId1")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Schedule")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeScheduleTypeId");

                    b.HasIndex("EnterpriseEmployeeId1");

                    b.ToTable("EmployeeSchedules");
                });

            modelBuilder.Entity("new_usaha.Domain.Entities.EmployeeScheduleType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("EmployeeScheduleTypes");
                });

            modelBuilder.Entity("new_usaha.Domain.Entities.Enterprise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("EnterpriseTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Photo")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("UserOwnerId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("EnterpriseTypeId");

                    b.ToTable("Enterprises");
                });

            modelBuilder.Entity("new_usaha.Domain.Entities.EnterpriseAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("EnterpriseId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SubDistrict")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("EnterpriseId");

                    b.ToTable("EnterpriseAddresses");
                });

            modelBuilder.Entity("new_usaha.Domain.Entities.EnterpriseClaim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Context")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EnterpriseTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Feature")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("EnterpriseTypeId");

                    b.ToTable("EnterpriseClaims");
                });

            modelBuilder.Entity("new_usaha.Domain.Entities.EnterpriseEmployee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("EnterpriseId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("EnterpriseRoleId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("EnterpriseId");

                    b.HasIndex("EnterpriseRoleId");

                    b.ToTable("EnterpriseEmployees");
                });

            modelBuilder.Entity("new_usaha.Domain.Entities.EnterpriseEmployeeRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("EnterpriseEmployeeId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("EnterpriseRoleId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("EnterpriseEmployeeId");

                    b.HasIndex("EnterpriseRoleId");

                    b.ToTable("EnterpriseEmployeeRoles");
                });

            modelBuilder.Entity("new_usaha.Domain.Entities.EnterpriseRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("EnterpriseId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("EnterpriseId");

                    b.ToTable("EnterpriseRoles");
                });

            modelBuilder.Entity("new_usaha.Domain.Entities.EnterpriseRoleClaim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("EnterpriseClaimId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("EnterpriseRoleId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("EnterpriseClaimId");

                    b.HasIndex("EnterpriseRoleId");

                    b.ToTable("EnterpriseRoleClaims");
                });

            modelBuilder.Entity("new_usaha.Domain.Entities.EnterpriseShift", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("EnterpriseId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<long>("Number")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("EnterpriseId");

                    b.ToTable("EnterpriseShifts");
                });

            modelBuilder.Entity("new_usaha.Domain.Entities.EnterpriseType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Provide")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("EnterpriseTypes");
                });

            modelBuilder.Entity("new_usaha.Domain.Entities.Goods", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("AvailableOnline")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Contain")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("EnterpriseId")
                        .HasColumnType("char(36)");

                    b.Property<int>("GoodsTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsWholesalerPriceAuto")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<Guid?>("ParentGoodsId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("EnterpriseId");

                    b.HasIndex("GoodsTypeId");

                    b.HasIndex("ParentGoodsId");

                    b.ToTable("Goodses");
                });

            modelBuilder.Entity("new_usaha.Domain.Entities.GoodsAdjustment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("DeltaStock")
                        .HasColumnType("int");

                    b.Property<Guid>("GoodsId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("GoodsId");

                    b.ToTable("GoodsAdjustments");
                });

            modelBuilder.Entity("new_usaha.Domain.Entities.GoodsGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("EnterpriseId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("EnterpriseId");

                    b.ToTable("GoodsGroups");
                });

            modelBuilder.Entity("new_usaha.Domain.Entities.GoodsGroupMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("GoodsGroupId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("GoodsId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("GoodsGroupId");

                    b.HasIndex("GoodsId");

                    b.ToTable("GoodsGroupMembers");
                });

            modelBuilder.Entity("new_usaha.Domain.Entities.GoodsOrdered", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("DiscountItem")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("DiscountItemTotal")
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid>("GoodsId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsWholesalerPrice")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("N")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("PricePerItem")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PricePerItemAfterDiscount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PriceTotal")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PriceTotalAfterDiscount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PriceTotalFinal")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("GoodsId");

                    b.HasIndex("OrderId");

                    b.ToTable("GoodsOrdereds");
                });

            modelBuilder.Entity("new_usaha.Domain.Entities.GoodsPhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("GoodsId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("GoodsId");

                    b.ToTable("GoodsPhotos");
                });

            modelBuilder.Entity("new_usaha.Domain.Entities.GoodsPrice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("End")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("GoodsId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("GoodsId");

                    b.ToTable("GoodsPrices");
                });

            modelBuilder.Entity("new_usaha.Domain.Entities.GoodsStock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("GoodsId")
                        .HasColumnType("char(36)");

                    b.Property<int>("N")
                        .HasColumnType("int");

                    b.Property<int>("Threshold")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GoodsId")
                        .IsUnique();

                    b.ToTable("GoodsStocks");
                });

            modelBuilder.Entity("new_usaha.Domain.Entities.GoodsType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("ParentGoodsTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentGoodsTypeId");

                    b.ToTable("GoodsTypes");
                });

            modelBuilder.Entity("new_usaha.Domain.Entities.GoodsWholesalePrice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("End")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("GoodsId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("WholesalerMin")
                        .HasColumnType("int");

                    b.Property<decimal>("WholesalerPrice")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("GoodsId");

                    b.ToTable("GoodsWholesalePrices");
                });

            modelBuilder.Entity("new_usaha.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("EnterpriseId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("Payment")
                        .HasColumnType("decimal(18,4)");

                    b.Property<uint>("PaymentMethodId")
                        .HasColumnType("int unsigned");

                    b.Property<decimal>("Return")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("To")
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid?>("UserOrderId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("EnterpriseId");

                    b.HasIndex("PaymentMethodId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("new_usaha.Domain.Entities.OrderProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("char(36)");

                    b.Property<uint>("OrderStatusId")
                        .HasColumnType("int unsigned");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("OrderStatusId");

                    b.ToTable("OrderProgresses");
                });

            modelBuilder.Entity("new_usaha.Domain.Entities.OrderStatus", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("NoQueue")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("OrderStatuses");
                });

            modelBuilder.Entity("new_usaha.Domain.Entities.PaymentMethod", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("PaymentMethods");
                });

            modelBuilder.Entity("new_usaha.Domain.Entities.Profit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("GoodsId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GoodsId");

                    b.ToTable("Profit");
                });

            modelBuilder.Entity("new_usaha.Domain.Entities.AddStockHistory", b =>
                {
                    b.HasOne("new_usaha.Domain.Entities.GoodsStock", "GoodsStock")
                        .WithMany("AddStockHistories")
                        .HasForeignKey("GoodsStockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GoodsStock");
                });

            modelBuilder.Entity("new_usaha.Domain.Entities.EmployeeJoin", b =>
                {
                    b.HasOne("new_usaha.Domain.Entities.Enterprise", "Enterprise")
                        .WithMany()
                        .HasForeignKey("EnterpriseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("new_usaha.Domain.Entities.EnterpriseRole", "EnterpriseRole")
                        .WithMany("EmployeeJoins")
                        .HasForeignKey("EnterpriseRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enterprise");

                    b.Navigation("EnterpriseRole");
                });

            modelBuilder.Entity("new_usaha.Domain.Entities.EmployeePresence", b =>
                {
                    b.HasOne("new_usaha.Domain.Entities.EmployeePresenceCode", "EmployeePresenceCode_End")
                        .WithMany()
                        .HasForeignKey("EmployeePresenceCode_EndId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("new_usaha.Domain.Entities.EmployeePresenceCode", "EmployeePresenceCode_Start")
                        .WithMany()
                        .HasForeignKey("EmployeePresenceCode_StartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_EmployeePresences_EmployeePresenceCodes_EmployeePresenceCod~1");

                    b.HasOne("new_usaha.Domain.Entities.EnterpriseEmployee", "EnterpriseEmployee")
                        .WithMany("EmployeePresences")
                        .HasForeignKey("EnterpriseEmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmployeePresenceCode_End");

                    b.Navigation("EmployeePresenceCode_Start");

                    b.Navigation("EnterpriseEmployee");
                });

            modelBuilder.Entity("new_usaha.Domain.Entities.EmployeePresenceCode", b =>
                {
                    b.HasOne("new_usaha.Domain.Entities.Enterprise", "Enterprise")
                        .WithMany("EmployeePresenceCodes")
                        .HasForeignKey("EnterpriseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enterprise");
                });

            modelBuilder.Entity("new_usaha.Domain.Entities.EmployeeSchedule", b =>
                {
                    b.HasOne("new_usaha.Domain.Entities.EmployeeScheduleType", "EmployeeScheduleType")
                        .WithMany("EmployeeSchedules")
                        .HasForeignKey("EmployeeScheduleTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("new_usaha.Domain.Entities.EnterpriseEmployee", "EnterpriseEmployee")
                        .WithMany("EmployeeSchedules")
                        .HasForeignKey("EnterpriseEmployeeId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmployeeScheduleType");

                    b.Navigation("EnterpriseEmployee");
                });

            modelBuilder.Entity("new_usaha.Domain.Entities.Enterprise", b =>
                {
                    b.HasOne("new_usaha.Domain.Entities.EnterpriseType", "EnterpriseType")
                        .WithMany("Enterprises")
                        .HasForeignKey("EnterpriseTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnterpriseType");
                });

            modelBuilder.Entity("new_usaha.Domain.Entities.EnterpriseAddress", b =>
                {
                    b.HasOne("new_usaha.Domain.Entities.Enterprise", "Enterprise")
                        .WithMany("EnterpriseAddresses")
                        .HasForeignKey("EnterpriseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enterprise");
                });

            modelBuilder.Entity("new_usaha.Domain.Entities.EnterpriseClaim", b =>
                {
                    b.HasOne("new_usaha.Domain.Entities.EnterpriseType", "EnterpriseType")
                        .WithMany("EnterpriseClaims")
                        .HasForeignKey("EnterpriseTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnterpriseType");
                });

            modelBuilder.Entity("new_usaha.Domain.Entities.EnterpriseEmployee", b =>
                {
                    b.HasOne("new_usaha.Domain.Entities.Enterprise", "Enterprise")
                        .WithMany("EnterpriseEmployees")
                        .HasForeignKey("EnterpriseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("new_usaha.Domain.Entities.EnterpriseRole", "EnterpriseRole")
                        .WithMany("EnterpriseEmployees")
                        .HasForeignKey("EnterpriseRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enterprise");

                    b.Navigation("EnterpriseRole");
                });

            modelBuilder.Entity("new_usaha.Domain.Entities.EnterpriseEmployeeRole", b =>
                {
                    b.HasOne("new_usaha.Domain.Entities.EnterpriseEmployee", "EnterpriseEmployee")
                        .WithMany()
                        .HasForeignKey("EnterpriseEmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("new_usaha.Domain.Entities.EnterpriseRole", "EnterpriseRole")
                        .WithMany("EnterpriseEmployeeRoles")
                        .HasForeignKey("EnterpriseRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnterpriseEmployee");

                    b.Navigation("EnterpriseRole");
                });

            modelBuilder.Entity("new_usaha.Domain.Entities.EnterpriseRole", b =>
                {
                    b.HasOne("new_usaha.Domain.Entities.Enterprise", "Enterprise")
                        .WithMany()
                        .HasForeignKey("EnterpriseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enterprise");
                });

            modelBuilder.Entity("new_usaha.Domain.Entities.EnterpriseRoleClaim", b =>
                {
                    b.HasOne("new_usaha.Domain.Entities.EnterpriseClaim", "EnterpriseClaim")
                        .WithMany("EnterpriseRoleClaims")
                        .HasForeignKey("EnterpriseClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("new_usaha.Domain.Entities.EnterpriseRole", "EnterpriseRole")
                        .WithMany("EnterpriseRoleClaims")
                        .HasForeignKey("EnterpriseRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnterpriseClaim");

                    b.Navigation("EnterpriseRole");
                });

            modelBuilder.Entity("new_usaha.Domain.Entities.EnterpriseShift", b =>
                {
                    b.HasOne("new_usaha.Domain.Entities.Enterprise", "Enterprise")
                        .WithMany("EnterpriseShifts")
                        .HasForeignKey("EnterpriseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enterprise");
                });

            modelBuilder.Entity("new_usaha.Domain.Entities.Goods", b =>
                {
                    b.HasOne("new_usaha.Domain.Entities.Enterprise", "Enterprise")
                        .WithMany("Goodses")
                        .HasForeignKey("EnterpriseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("new_usaha.Domain.Entities.GoodsType", "GoodsType")
                        .WithMany("Goodses")
                        .HasForeignKey("GoodsTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("new_usaha.Domain.Entities.Goods", "ParentGoods")
                        .WithMany("ChildrenGoods")
                        .HasForeignKey("ParentGoodsId");

                    b.Navigation("Enterprise");

                    b.Navigation("GoodsType");

                    b.Navigation("ParentGoods");
                });

            modelBuilder.Entity("new_usaha.Domain.Entities.GoodsAdjustment", b =>
                {
                    b.HasOne("new_usaha.Domain.Entities.Goods", "Goods")
                        .WithMany()
                        .HasForeignKey("GoodsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Goods");
                });

            modelBuilder.Entity("new_usaha.Domain.Entities.GoodsGroup", b =>
                {
                    b.HasOne("new_usaha.Domain.Entities.Enterprise", "Enterprise")
                        .WithMany()
                        .HasForeignKey("EnterpriseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enterprise");
                });

            modelBuilder.Entity("new_usaha.Domain.Entities.GoodsGroupMember", b =>
                {
                    b.HasOne("new_usaha.Domain.Entities.GoodsGroup", "GoodsGroup")
                        .WithMany("Members")
                        .HasForeignKey("GoodsGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("new_usaha.Domain.Entities.Goods", "Goods")
                        .WithMany("GoodsGroupMembers")
                        .HasForeignKey("GoodsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Goods");

                    b.Navigation("GoodsGroup");
                });

            modelBuilder.Entity("new_usaha.Domain.Entities.GoodsOrdered", b =>
                {
                    b.HasOne("new_usaha.Domain.Entities.Goods", "Goods")
                        .WithMany("GoodsOrdereds")
                        .HasForeignKey("GoodsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("new_usaha.Domain.Entities.Order", "Order")
                        .WithMany("GoodsOrdereds")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Goods");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("new_usaha.Domain.Entities.GoodsPhoto", b =>
                {
                    b.HasOne("new_usaha.Domain.Entities.Goods", "Goods")
                        .WithMany("GoodsPhotos")
                        .HasForeignKey("GoodsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Goods");
                });

            modelBuilder.Entity("new_usaha.Domain.Entities.GoodsPrice", b =>
                {
                    b.HasOne("new_usaha.Domain.Entities.Goods", "Goods")
                        .WithMany("GoodsPrices")
                        .HasForeignKey("GoodsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Goods");
                });

            modelBuilder.Entity("new_usaha.Domain.Entities.GoodsStock", b =>
                {
                    b.HasOne("new_usaha.Domain.Entities.Goods", "Goods")
                        .WithOne("GoodsStock")
                        .HasForeignKey("new_usaha.Domain.Entities.GoodsStock", "GoodsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Goods");
                });

            modelBuilder.Entity("new_usaha.Domain.Entities.GoodsType", b =>
                {
                    b.HasOne("new_usaha.Domain.Entities.GoodsType", "ParentGoodsType")
                        .WithMany("SubGoodsTypes")
                        .HasForeignKey("ParentGoodsTypeId");

                    b.Navigation("ParentGoodsType");
                });

            modelBuilder.Entity("new_usaha.Domain.Entities.GoodsWholesalePrice", b =>
                {
                    b.HasOne("new_usaha.Domain.Entities.Goods", "Goods")
                        .WithMany("GoodsWholesalePrices")
                        .HasForeignKey("GoodsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Goods");
                });

            modelBuilder.Entity("new_usaha.Domain.Entities.Order", b =>
                {
                    b.HasOne("new_usaha.Domain.Entities.Enterprise", "Enterprise")
                        .WithMany("Orders")
                        .HasForeignKey("EnterpriseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("new_usaha.Domain.Entities.PaymentMethod", "PaymentMethod")
                        .WithMany("Orders")
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enterprise");

                    b.Navigation("PaymentMethod");
                });

            modelBuilder.Entity("new_usaha.Domain.Entities.OrderProgress", b =>
                {
                    b.HasOne("new_usaha.Domain.Entities.Order", "Order")
                        .WithMany("OrderProgresses")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("new_usaha.Domain.Entities.OrderStatus", "OrderStatus")
                        .WithMany("OrderProgresses")
                        .HasForeignKey("OrderStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("OrderStatus");
                });

            modelBuilder.Entity("new_usaha.Domain.Entities.Profit", b =>
                {
                    b.HasOne("new_usaha.Domain.Entities.Goods", "Goods")
                        .WithMany("GoodsProfits")
                        .HasForeignKey("GoodsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Goods");
                });

            modelBuilder.Entity("new_usaha.Domain.Entities.EmployeeScheduleType", b =>
                {
                    b.Navigation("EmployeeSchedules");
                });

            modelBuilder.Entity("new_usaha.Domain.Entities.Enterprise", b =>
                {
                    b.Navigation("EmployeePresenceCodes");

                    b.Navigation("EnterpriseAddresses");

                    b.Navigation("EnterpriseEmployees");

                    b.Navigation("EnterpriseShifts");

                    b.Navigation("Goodses");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("new_usaha.Domain.Entities.EnterpriseClaim", b =>
                {
                    b.Navigation("EnterpriseRoleClaims");
                });

            modelBuilder.Entity("new_usaha.Domain.Entities.EnterpriseEmployee", b =>
                {
                    b.Navigation("EmployeePresences");

                    b.Navigation("EmployeeSchedules");
                });

            modelBuilder.Entity("new_usaha.Domain.Entities.EnterpriseRole", b =>
                {
                    b.Navigation("EmployeeJoins");

                    b.Navigation("EnterpriseEmployeeRoles");

                    b.Navigation("EnterpriseEmployees");

                    b.Navigation("EnterpriseRoleClaims");
                });

            modelBuilder.Entity("new_usaha.Domain.Entities.EnterpriseType", b =>
                {
                    b.Navigation("EnterpriseClaims");

                    b.Navigation("Enterprises");
                });

            modelBuilder.Entity("new_usaha.Domain.Entities.Goods", b =>
                {
                    b.Navigation("ChildrenGoods");

                    b.Navigation("GoodsGroupMembers");

                    b.Navigation("GoodsOrdereds");

                    b.Navigation("GoodsPhotos");

                    b.Navigation("GoodsPrices");

                    b.Navigation("GoodsProfits");

                    b.Navigation("GoodsStock")
                        .IsRequired();

                    b.Navigation("GoodsWholesalePrices");
                });

            modelBuilder.Entity("new_usaha.Domain.Entities.GoodsGroup", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("new_usaha.Domain.Entities.GoodsStock", b =>
                {
                    b.Navigation("AddStockHistories");
                });

            modelBuilder.Entity("new_usaha.Domain.Entities.GoodsType", b =>
                {
                    b.Navigation("Goodses");

                    b.Navigation("SubGoodsTypes");
                });

            modelBuilder.Entity("new_usaha.Domain.Entities.Order", b =>
                {
                    b.Navigation("GoodsOrdereds");

                    b.Navigation("OrderProgresses");
                });

            modelBuilder.Entity("new_usaha.Domain.Entities.OrderStatus", b =>
                {
                    b.Navigation("OrderProgresses");
                });

            modelBuilder.Entity("new_usaha.Domain.Entities.PaymentMethod", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
